language: go

go:
  - "1.14.x"

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - GOLANGCI_LINT_VERSION=1.23.0
    - GO111MODULE=on

install:
  # - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ${TRAVIS_HOME}/bin v${GOLANGCI_LINT_VERSION}
  - echo "skip install"

script:
  # - golangci-lint run --config .golangci.yml
  - go test -v ./...

after_success:
  - docker --version
  - docker build -f Dockerfile --label "commit=$TRAVIS_COMMIT" -t kybernetwork/cclog:$TRAVIS_COMMIT .

deploy:
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop|staging|master$
