name: Build and Test
on:
  push:
    branches:
      - master
      - staging
      - develop
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
        env:
          GOROOT: ""
        with:
          args: run --config .golangci.yml ./...
          golangci_lint_version: v1.23

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: go test -v ./...

  deploy:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        env:

        run: |
          cd cmd/cclog-server
          go build -ldflags '-linkmode external -w -extldflags "-static"'
#          docker build -t asia.gcr.io/$GCLOUD_PROJECT/market_data:1.0 .
#          docker push asia.gcr.io/$GCLOUD_PROJECT/market_data:1.0